/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface MaterialIcon {
      'name': string;
      'size': string;
    }
  }

  interface HTMLMaterialIconElement extends StencilComponents.MaterialIcon, HTMLStencilElement {}

  var HTMLMaterialIconElement: {
    prototype: HTMLMaterialIconElement;
    new (): HTMLMaterialIconElement;
  };
  interface HTMLElementTagNameMap {
    'material-icon': HTMLMaterialIconElement;
  }
  interface ElementTagNameMap {
    'material-icon': HTMLMaterialIconElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'material-icon': JSXElements.MaterialIconAttributes;
    }
  }
  namespace JSXElements {
    export interface MaterialIconAttributes extends HTMLAttributes {
      'name'?: string;
      'size'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;